name: gazelle_jwt
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.3.2

# Add regular dependencies here.
dependencies:
  dart_jsonwebtoken: ^2.13.0
  gazelle_core:
    path: ../gazelle_core
  # path: ^1.8.0

dev_dependencies:
  http: ^1.2.1
  lints: ^3.0.0
  test: ^1.24.0
