name: gazelle_jwt
description: Simple and easy JWT plugin for Gazelle. 
version: 0.1.0
repository: https://github.com/intales/gazelle/tree/main/packages/gazelle_jwt

environment:
  sdk: ^3.3.2

dependencies:
  dart_jsonwebtoken: ^2.13.0
  gazelle_core: ^0.1.1

dev_dependencies:
  http: ^1.2.1
  lints: ^3.0.0
  test: ^1.24.0
