name: Continuous Integration Pipeline

on:
  push:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dart setup
        uses: dart-lang/setup-dart@v1

      - name: Melos setup
        run: dart pub global activate melos

      - name: Melos bootstrap
        run: melos bootstrap

      - name: Run tests
        run: melos run test
